apiVersion: v1
kind: Service
metadata:
  name: challenge-service
spec:
  selector:
    app: challenge
  ports:
    - protocol: TCP
      port: {{ (index .Values.challenge.ports 0).port }}
      targetPort: {{ (index .Values.challenge.ports 0).targetPort }}
  type: ClusterIP