apiVersion: v1
kind: Service
metadata:
  name: program-service
spec:
  selector:
    app: program
  ports:
    - protocol: TCP
      port: {{ (index .Values.program.ports 0).port }}
      targetPort: {{ (index .Values.program.ports 0).targetPort }}
  type: ClusterIP