apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  selector:
    app: inventory
  ports:
    - protocol: TCP
      port: {{ (index .Values.inventory.ports 0).port }}
      targetPort: {{ (index .Values.inventory.ports 0).targetPort }}
  type: ClusterIP