apiVersion: v2
name: exercise-record
description: ExerciseRecord's Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 62
maintainers:
  - name: Jaesin Lee
    email: jaesin463@gmail.com