apiVersion: apps/v1
kind: Deployment
metadata:
  name: exercise-record-deployment
spec:
  replicas: {{ .Values.exerciseRecord.replicas }}
  selector:
    matchLabels:
      app: exercise-record
  template:
    metadata:
      labels:
        app: exercise-record
    spec:
      containers:
      - name: exercise-record
        image: {{ .Values.exerciseRecord.image.repository }}:{{ .Chart.AppVersion }}
        env:
          - name: DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: exercise-record-app-secrets
                key: database.username
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: exercise-record-app-secrets
                key: database.password
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: exercise-record-app-secrets
                key: database.url
          - name: DATABASE_PORT
            valueFrom:
              secretKeyRef:
                name: exercise-record-app-secrets
                key: database.port
          - name: DATABASE_USER_DB_NAME
            valueFrom:
              secretKeyRef:
                name: exercise-record-app-secrets
                key: database.dbName
        ports:
          - containerPort: {{ (index .Values.exerciseRecord.ports 0).port }}
