apiVersion: v1
kind: Service
metadata:
  name: exercise-record-service
spec:
  selector:
    app: exercise-record
  ports:
    - protocol: TCP
      port: {{ (index .Values.exerciseRecord.ports 0).port }}
      targetPort: {{ (index .Values.exerciseRecord.ports 0).targetPort }}
  type: ClusterIP