apiVersion: v1
kind: Service
metadata:
  name: fcm-service
spec:
  selector:
    app: fcm
  ports:
    - protocol: TCP
      port: {{ (index .Values.fcm.ports 0).port }}
      targetPort: {{ (index .Values.fcm.ports 0).targetPort }}
  type: ClusterIP